
import qrcode
"""from flask import Flask, render_template

app = Flask(__name__)

menu_categories = [
    "ΚΑΦΕΔΕΣ",
    "ΡΟΦΗΜΑΤΑ",
    "ΑΝΑΨΥΚΤΙΚΑ",
    "ΜΠΥΡΕΣ",
    "COCKTAILS",
    "BURGER",
    "ΠΙΤΣΕΣ",
    "SUSHI",
    "ΓΛΥΚΑ",
    "PANCAKES"
]

@app.route('/')
def home():
    return render_template(
        'index.html',
        categories=menu_categories
    )

if __name__ == '__main__':
    app.run(debug=True)"""

from flask import Flask, render_template, abort

app = Flask(__name__)


menu_categories = [
    "ΚΑΦΕΔΕΣ", "ΡΟΦΗΜΑΤΑ", "ΑΝΑΨΥΚΤΙΚΑ", "ΜΠΥΡΕΣ",
    "ΚΡΑΣΙΑ", "ΟΥΖΟ-ΤΣΙΠΟΥΡΟ", "ΠΟΤΑ", "COCKTAILS", "ΣΦΗΝΑΚΙΑ",
    "ΣΟΥΒΛΑΚΙ-ΨΗΣΤΑΡΙΑ", "BURGERS", "ΠΙΤΣΕΣ", "SUSHI", "ΓΛΥΚΑ", "PANCAKES"
]

# Όλα τα προϊόντα σου με τις τιμές τους (χρησιμοποιήθηκε η τιμή για τη Σάλα)
menu_products = {
    "ΚΑΦΕΔΕΣ": [
        {"name": "ΕΛΛΗΝΙΚΟΣ ΜΟΝΟΣ", "price": "3.00€", "description": ""},
        {"name": "ΕΛΛΗΝΙΚΟΣ ΔΙΠΛΟΣ", "price": "3.50€", "description": ""},
        {"name": "NESCAFE", "price": "3.50€", "description": ""},
        {"name": "ΦΡΑΠΕ", "price": "3.50€", "description": ""},
        {"name": "ESPRESSO MONO", "price": "3.00€", "description": ""},
        {"name": "ESPRESSO ΔΙΠΛΟ", "price": "3.50€", "description": ""},
        {"name": "ESPRESSO LUGO", "price": "3.50€", "description": ""},
        {"name": "FREDDO ESPRESSO", "price": "4.00€", "description": ""},
        {"name": "FREDDO ESPRESSO GRANDE", "price": "4.50€", "description": ""},
        {"name": "CAPPUCCINO MONO", "price": "3.50€", "description": ""},
        {"name": "CAPPUCCINO ΔΙΠΛΟ", "price": "4.50€", "description": ""},
        {"name": "FREDDO CAPPUCCINO", "price": "4.50€", "description": ""},
        {"name": "FREDDO CAPP GRANDE", "price": "5.50€", "description": ""},
        {"name": "AMERICANO ΔΙΠΛΟ", "price": "4.00€", "description": ""},
        {"name": "LATTE ΜΟΝΟ", "price": "4.00€", "description": ""},
        {"name": "HOT LATTE", "price": "4.00€", "description": ""},
        {"name": "ICE LATTE", "price": "4.50€", "description": ""},
        {"name": "ICE LATTE ΜΟΝΟ", "price": "4.00€", "description": ""},
        {"name": "MACCHIATO", "price": "3.00€", "description": ""},
        {"name": "MOCHA", "price": "4.50€", "description": ""},
        {"name": "MOCHACHINO ΖΕΣΤΟ", "price": "4.00€", "description": ""},
        {"name": "MOCHACHINO", "price": "4.50€", "description": ""},
        {"name": "ΓΑΛΛΙΚΟΣ", "price": "3.50€", "description": ""},
        {"name": "AFFOGATO", "price": "5.00€", "description": ""},
        {"name": "KAFES", "price": "4.00€", "description": ""},
        {"name": "ΤΕΤΡΑΠΛΟ", "price": "4.50€", "description": ""}
    ],
    "ΡΟΦΗΜΑΤΑ": [
        {"name": "ΤΣΑΙ ΖΕΣΤΟ", "price": "3.50€", "description": ""},
        {"name": "ΣΟΚΟΛΑΤΑ", "price": "4.50€", "description": ""},
        {"name": "ΣΟΚΟΛΑΤΑ ΛΕΥΚΗ", "price": "4.50€", "description": ""},
        {"name": "ΣΟΚΟΛΑΤΑ VENUA", "price": "5.00€", "description": ""},
        {"name": "ΚΑΚΑΟ", "price": "4.00€", "description": ""},
        {"name": "MILKSHAKE", "price": "5.50€", "description": ""},
        {"name": "FREDDITO", "price": "5.50€", "description": ""},
        {"name": "ΓΡΑΝΙΤΑ", "price": "5.50€", "description": ""},
        {"name": "FRUIT PUNCH", "price": "5.50€", "description": ""},
        {"name": "ΦΥΣΙΚΟΣ ΧΥΜΟΣ ΠΟΡΤΟΚΑΛΙ", "price": "5.50€", "description": ""},
        {"name": "ΦΥΣΙΚΟΣ ΧΥΜΟΣ ΜΠΑΝΑΝΑ", "price": "4.00€", "description": ""},
        {"name": "ΦΥΣΙΚΟΣ ΑΝΑΜΕΙΚΤΟΣ", "price": "6.00€", "description": ""},
        {"name": "ΤΥΠΟΠΟΙΗΜΕΝΟΣ ΧΥΜΟΣ", "price": "4.00€", "description": ""},
        {"name": "ΤΥΠΟΠΟΙΗΜΕΝΟΣ ΑΝΑΜΕΙΚΤΟΣ", "price": "3.00€", "description": ""},
        {"name": "SM. ALL DAY CHOCO", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. MELON SPLASH", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. FITNESS DELIGHT", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. TROPICAL BOOST", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. BERRY RED", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. VANILLA SUNSET", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. GREEN ENERGY", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. STRAW BASIL", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. PEANUT BUTTER CAKE", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. BERRY LIME PIE", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. CHOCOLATE CAKE", "price": "6.00€", "description": "Smoothie"},
        {"name": "SM. BANOFFEE", "price": "6.00€", "description": "Smoothie"},
        {"name": "LEMON LEMONGRAND", "price": "3.00€", "description": ""}
    ],
    "ΑΝΑΨΥΚΤΙΚΑ": [
        {"name": "COCA COLA", "price": "3.50€", "description": ""},
        {"name": "COCA COLA ZERO", "price": "3.50€", "description": ""},
        {"name": "COCA COLA LIGHT", "price": "3.50€", "description": ""},
        {"name": "COCA COLA GOLD", "price": "3.50€", "description": ""},
        {"name": "COCA COLA ΚΟΥΤΙ 330ML", "price": "2.50€", "description": ""},
        {"name": "COCA COLA 1.5 LT", "price": "3.50€", "description": ""},
        {"name": "ΠΟΡΤΟΚΑΛΑΔΑ", "price": "3.50€", "description": ""},
        {"name": "ΠΟΡΤΟΚΑΛΑΔΑ ΧΩΡΙΣ ΑΝΘΡΑΚΙΚΟ", "price": "3.50€", "description": ""},
        {"name": "ΛΕΜΟΝΑΔΑ", "price": "3.50€", "description": ""},
        {"name": "ΣΠΙΤΙΚΗ ΛΕΜΟΝΑΔΑ", "price": "5.00€", "description": ""},
        {"name": "SPRITE", "price": "3.50€", "description": ""},
        {"name": "ΣΟΔΑ", "price": "3.50€", "description": ""},
        {"name": "ΤΟΝΙΚ", "price": "3.50€", "description": ""},
        {"name": "PERRIER", "price": "3.50€", "description": ""},
        {"name": "SWEPPERS", "price": "3.50€", "description": ""},
        {"name": "SWEPPSE ΓΚΡΕΙΠΦΡΟΥΤ", "price": "3.50€", "description": ""},
        {"name": "BITTER LEMON", "price": "3.50€", "description": ""},
        {"name": "RED BULL", "price": "5.00€", "description": ""},
        {"name": "ΚΡΗΝΗ ΠΟΡΤΟΚΑΛΑΔΑ", "price": "3.50€", "description": ""},
        {"name": "ΚΡΗΝΗ ΛΕΜΟΝΑΔΑ", "price": "3.50€", "description": ""},
        {"name": "ICE TEA LEMONI", "price": "4.50€", "description": ""},
        {"name": "ICE TEA ΡΟΔΑΚΙΝΟ", "price": "4.50€", "description": ""},
        {"name": "ICE TEA ΠΡΑΣΙΝΟ", "price": "4.00€", "description": ""},
        {"name": "ICE TEA PASSION FRUIT", "price": "4.00€", "description": ""},
        {"name": "ICE TEA ΚΑΡΠΟΥΖΙ ΜΕΝΤΑ", "price": "4.00€", "description": ""},
        {"name": "ICE TEA LEMON LOUIZA", "price": "4.00€", "description": ""},
        {"name": "ICE TEA LEMON POMENGRANDE", "price": "4.00€", "description": ""},
        {"name": "ΝΕΡΟ 0.50ml", "price": "0.50€", "description": ""},
        {"name": "ΝΕΡΟ 1LT", "price": "1.50€", "description": ""}
    ],
    "ΜΠΥΡΕΣ": [
        {"name": "KAISER", "price": "4.50€", "description": ""},
        {"name": "ΑΛΦΑ WEISS", "price": "5.00€", "description": ""},
        {"name": "ΑΛΦΑ 330ml", "price": "4.00€", "description": ""},
        {"name": "ΑΛΦΑ ΑΛΑΤΙ", "price": "4.00€", "description": ""},
        {"name": "ΑΛΦΑ FREE", "price": "4.00€", "description": ""},
        {"name": "ΒΕΡΓΙΝΑ WEISS", "price": "6.00€", "description": ""},
        {"name": "ΒΕΡΓΙΝΑ", "price": "4.00€", "description": ""},
        {"name": "ΒΕΡΓΙΝΑ BLACK", "price": "0.00€", "description": ""},
        {"name": "HEINEKEN FREE", "price": "0.00€", "description": ""},
        {"name": "HAINEKEN FREE (ΚΟΥΤΙ/ΜΠΟΥΚΑΛΙ)", "price": "4.00€", "description": ""},
        {"name": "HEINEKEN 330ml", "price": "4.00€", "description": ""},
        {"name": "HEINEKEN SILVER 330ml", "price": "3.50€", "description": ""},
        {"name": "AMSTEL RADLER", "price": "4.00€", "description": ""},
        {"name": "AMSTEL 330ml", "price": "4.00€", "description": ""},
        {"name": "PAULANER", "price": "3.50€", "description": ""},
        {"name": "KORONA", "price": "7.00€", "description": ""},
        {"name": "CORONA", "price": "5.00€", "description": ""},
        {"name": "SOL", "price": "7.00€", "description": ""},
        {"name": "ΜΥΘΟΣ 330ml", "price": "4.00€", "description": ""},
        {"name": "FIX 330ml", "price": "4.00€", "description": ""},
        {"name": "FISHER 330ml", "price": "4.00€", "description": ""},
        {"name": "DESPERADOS 330ml", "price": "4.50€", "description": ""},
        {"name": "ΜΑΜΟΣ", "price": "4.00€", "description": ""},
        {"name": "STELLA", "price": "4.00€", "description": ""},
        {"name": "ΒΑΡΕΛΙ 330ml", "price": "4.00€", "description": ""},
        {"name": "ΒΑΡΕΛΙ 500ml", "price": "5.00€", "description": ""},
        {"name": "ΜΠΥΡΑ 330ml ΚΟΥΤΑΚΙ ΠΑΚΕΤΟ", "price": "2.50€", "description": ""},
        {"name": "ΛΗΜΝΙΑ 330ML", "price": "5.50€", "description": ""}
    ],
    "ΚΡΑΣΙΑ": [
        {"name": "ΠΟΤΗΡΙ ΛΕΥΚΟ ΕΝΩΣΗΣ", "price": "4.00€", "description": ""},
        {"name": "ΠΟΤΗΡΙ ΛΕΥΚΟ ΚΟΥΚΟΥΛΗΘΡΑ", "price": "3.50€", "description": ""},
        {"name": "ΠΟΤΗΡΙ ΛΕΥΚΟ ΧΑΤΖΗΓΕΩΡΓΙΟΥ", "price": "4.00€", "description": ""},
        {"name": "ΠΟΤΗΡΙ ΗΜΙΓΛΥΚΟ ΕΝΩΣΗΣ", "price": "4.00€", "description": ""},
        {"name": "ΠΟΤΗΡΙ ΚΟΚΚΙΝΟ ΕΝΩΣΗ", "price": "4.00€", "description": ""},
        {"name": "ΠΟΤΗΡΙ ΣΑΓΚΡΙΑ", "price": "4.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΚΡΑΣΙ ΛΗΜΝΙΑ ΓΗ", "price": "40.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΚΡΑΣΙ ΑΡΩΜΑ ΛΗΜΝΟΥ", "price": "40.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΚΡΑΣΙ ΜΟΣΧΑΤΟ ΛΗΜΝΟΥ", "price": "40.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΚΡΑΣΙ ΛΑΓΟΠΑΤΙ", "price": "40.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΞΗΡΟ ΘΥΜΙΣΕΣ", "price": "40.00€", "description": ""},
        {"name": "ΚΟΚΚΙΝΟ ΞΗΡΟ ΛΗΜΝΙΑ ΓΗ", "price": "40.00€", "description": ""},
        {"name": "ΚΟΚΚΙΝΟ ΞΗΡΟ ΘΥΜΙΣΕΣ", "price": "40.00€", "description": ""},
        {"name": "ΡΟΖΕ ΞΗΡΟ ΛΗΜΝΙΑ ΓΗ", "price": "40.00€", "description": ""},
        {"name": "ΗΜΙΑΦΡΩΔΕΣ ΚΡΑΣΙ D IFESTIA", "price": "50.00€", "description": ""},
        {"name": "ΗΜΙΑΦΡΩΔΕΣ ΚΡΑΣΙ FRIZZANTE", "price": "40.00€", "description": ""},
        {"name": "ΗΜΙΑΦΡΩΔΕΣ D IFESTIA 200ml", "price": "9.00€", "description": ""},
        {"name": "ΦΡΙΖΑΝΤΕ (ΠΟΤΗΡΙ)", "price": "7.00€", "description": ""},
        {"name": "ΛΕΥΚΟ ΞΗΡΟ 1/2 ΛΙΤΡΟ", "price": "5.00€", "description": ""},
        {"name": "ΚΟΚΚΙΝΟ ΞΗΡΟ 1/2 ΛΙΤΡΟ", "price": "5.00€", "description": ""}
    ],
    "ΟΥΖΟ-ΤΣΙΠΟΥΡΟ": [
        {"name": "ΠΛΩΜΑΡΙ", "price": "5.00€", "description": ""},
        {"name": "ΟΥΖΟ ΜΙΝΙ", "price": "5.00€", "description": ""},
        {"name": "ΟΥΖΟ ME XYMO", "price": "6.00€", "description": ""},
        {"name": "ΤΣΙΠΟΥΡΟ ΚΟΥΚΟΥ ΜΕ ΜΕΖΕ", "price": "6.00€", "description": ""},
        {"name": "ΤΣΙΠΟΥΡΟ ΧΩΡΙΣ ΓΛΥΚΑΝΙΣΟ ΜΕΖΕ", "price": "6.00€", "description": ""}
    ],
    "ΠΟΤΑ": [
        {"name": "JOHNIE RED", "price": "8.00€", "description": ""},
        {"name": "FAMOUS", "price": "8.00€", "description": ""},
        {"name": "DEWARS", "price": "8.00€", "description": ""},
        {"name": "GRANTS", "price": "8.00€", "description": ""},
        {"name": "CUTTY SARK", "price": "8.00€", "description": ""},
        {"name": "HAIG", "price": "8.00€", "description": ""},
        {"name": "JAMESON", "price": "8.00€", "description": ""},
        {"name": "BLACK BARREL", "price": "9.00€", "description": ""},
        {"name": "BALLANTINES", "price": "8.00€", "description": ""},
        {"name": "CANADIAN", "price": "8.00€", "description": ""},
        {"name": "TEACHERS", "price": "8.00€", "description": ""},
        {"name": "TULAMORE", "price": "8.00€", "description": ""},
        {"name": "BELLS", "price": "7.00€", "description": ""},
        {"name": "GLENFIDICH", "price": "9.00€", "description": ""},
        {"name": "JOHNIE BLACK", "price": "9.00€", "description": ""},
        {"name": "JOHNIE DOUBLE BLACK", "price": "9.00€", "description": ""},
        {"name": "JOHNIE GOLD", "price": "11.00€", "description": ""},
        {"name": "CHIVAS", "price": "9.00€", "description": ""},
        {"name": "DIMPLE", "price": "9.00€", "description": ""},
        {"name": "CARDHU", "price": "9.00€", "description": ""},
        {"name": "JACK DANIELS", "price": "9.00€", "description": ""},
        {"name": "JACK DANIELS HONEY", "price": "9.00€", "description": ""},
        {"name": "JIN BEMM", "price": "8.00€", "description": ""},
        {"name": "GORDONS", "price": "8.00€", "description": ""},
        {"name": "GORDONS PINK", "price": "9.00€", "description": ""},
        {"name": "BEEFEATER", "price": "8.00€", "description": ""},
        {"name": "BOMBAY", "price": "9.00€", "description": ""},
        {"name": "BULLDOG", "price": "8.00€", "description": ""},
        {"name": "TANGEREY", "price": "9.00€", "description": ""},
        {"name": "HENDRICKS", "price": "10.00€", "description": ""},
        {"name": "SERKOVA", "price": "8.00€", "description": ""},
        {"name": "STOLICHNAYA", "price": "8.00€", "description": ""},
        {"name": "ABSOLUT", "price": "8.00€", "description": ""},
        {"name": "GREY GOOSE", "price": "12.00€", "description": ""},
        {"name": "BELVEDERE", "price": "12.00€", "description": ""},
        {"name": "BACARDI", "price": "8.00€", "description": ""},
        {"name": "BACARDI ΜΑΥΡΟ", "price": "8.00€", "description": ""},
        {"name": "HAVANA ΜΑΥΡΗ", "price": "9.00€", "description": ""},
        {"name": "HAVANA", "price": "8.00€", "description": ""},
        {"name": "BRUGAL", "price": "8.00€", "description": ""},
        {"name": "BRUGAL ΜΑΥΡΟ", "price": "8.00€", "description": ""},
        {"name": "CAPTAIN MORGAN", "price": "8.00€", "description": ""},
        {"name": "PLANTATION", "price": "8.00€", "description": ""},
        {"name": "SABUCA", "price": "8.00€", "description": ""},
        {"name": "SABUCA ΜΑΥΡΗ", "price": "8.00€", "description": ""},
        {"name": "BAILEYS", "price": "8.00€", "description": ""},
        {"name": "AMARRETO DISARONO", "price": "8.00€", "description": ""},
        {"name": "MARTINI BIANCO", "price": "8.00€", "description": ""},
        {"name": "MARTINI ROSSATO", "price": "8.00€", "description": ""},
        {"name": "DRAMBUIE", "price": "8.00€", "description": ""},
        {"name": "ΝΤΡΑΜΠΟΥΙ", "price": "9.00€", "description": ""},
        {"name": "CAMPARI", "price": "8.00€", "description": ""},
        {"name": "JEGERMAISTER", "price": "8.00€", "description": ""},
        {"name": "SOUTHERN COMFORT", "price": "8.00€", "description": ""},
        {"name": "MALIBU", "price": "8.00€", "description": ""},
        {"name": "URSUS", "price": "8.00€", "description": ""},
        {"name": "NORTH", "price": "8.00€", "description": ""},
        {"name": "KALUA", "price": "8.00€", "description": ""},
        {"name": "METAXA 5", "price": "8.00€", "description": ""},
        {"name": "METAXA 7", "price": "8.00€", "description": ""},
        {"name": "COINTREAU", "price": "8.00€", "description": ""},
        {"name": "FRANGELICA", "price": "8.00€", "description": ""},
        {"name": "TALISKER", "price": "11.00€", "description": ""},
        {"name": "LAGAVOULIN", "price": "15.00€", "description": ""},
        {"name": "GORDONS SPACE", "price": "7.00€", "description": ""},
        {"name": "KIWI", "price": "6.00€", "description": ""},
        {"name": "ΤΕΚΙΛΑ ΛΕΥΚΗ", "price": "8.00€", "description": ""},
        {"name": "ΤΕΚΙΛΑ ΚΙΤΡΙΝΗ", "price": "8.00€", "description": ""},
        {"name": "ΤΕΚΙΛΑ ΣΟΚΟΛΑΤΑ", "price": "7.00€", "description": ""},
        {"name": "ΜΑΣΤΙΧΑ ΧΙΟΥ", "price": "8.00€", "description": ""},
        {"name": "ΚΕΡΑΣΙ (ΛΙΚΕΡ)", "price": "8.00€", "description": ""},
        {"name": "ΚΙΤΡΟΝ ΝΑΞΟΥ", "price": "8.00€", "description": ""},
        {"name": "BLUE CARACAO", "price": "8.00€", "description": ""},
        {"name": "ΜΑΝΤΑΡΙΝΙ (ΛΙΚΕΡ)", "price": "8.00€", "description": ""},
        {"name": "ΛΙΚΕΡ ΚΑΚΑΟ", "price": "7.00€", "description": ""},
        {"name": "RAMAZZOTI ROSSATO", "price": "8.00€", "description": ""},
        {"name": "JOHNIE GOLD ΦΙΑΛΗ", "price": "120.00€", "description": ""},
        {"name": "JOHNIE WHITE ΦΙΑΛΗ", "price": "120.00€", "description": ""},
        {"name": "TALISKER ΦΙΑΛΗ", "price": "120.00€", "description": ""},
        {"name": "LAGAVOULIN ΦΙΑΛΗ", "price": "140.00€", "description": ""},
        {"name": "MOET ΠΡΑΣΙΝΗ", "price": "120.00€", "description": ""},
        {"name": "MOET ΑΣΠΡΗ", "price": "130.00€", "description": ""},
        {"name": "GORDONS PINK ΦΙΑΛΗ", "price": "80.00€", "description": ""}
    ],
    "COCKTAILS": [
        {"name": "TROPIC", "price": "10.00€", "description": ""},
        {"name": "EXOTIC", "price": "10.00€", "description": ""},
        {"name": "SURVIVORS", "price": "9.00€", "description": ""},
        {"name": "WATERMELON DREAM", "price": "10.00€", "description": ""},
        {"name": "MOJITO", "price": "9.00€", "description": ""},
        {"name": "CUBA LIBRE", "price": "9.00€", "description": ""},
        {"name": "MARGARITA", "price": "9.00€", "description": ""},
        {"name": "OLD FASHIONED", "price": "9.00€", "description": ""},
        {"name": "NEGRONI", "price": "10.00€", "description": ""},
        {"name": "DRY MARTINI", "price": "9.00€", "description": ""},
        {"name": "DAIQUIRI", "price": "9.00€", "description": ""},
        {"name": "DAIQUIRI ΦΡΑΟΥΛΑ", "price": "10.00€", "description": ""},
        {"name": "CAIPIRINHA", "price": "9.00€", "description": ""},
        {"name": "CAIPIROSKA", "price": "9.00€", "description": ""},
        {"name": "MOJITO FREE", "price": "5.00€", "description": ""},
        {"name": "PAINKILLER", "price": "9.00€", "description": ""},
        {"name": "HURRICANE", "price": "10.00€", "description": ""},
        {"name": "HANGOVER IN HAWAII", "price": "10.00€", "description": ""},
        {"name": "PINA KOLANTA", "price": "9.00€", "description": ""},
        {"name": "COSMOPOLITAN", "price": "10.00€", "description": ""},
        {"name": "MAI TAI", "price": "11.00€", "description": ""},
        {"name": "SEX ON THE BEACH", "price": "10.00€", "description": ""},
        {"name": "LONG ISLAND", "price": "10.00€", "description": ""},
        {"name": "MIAMI BEACH ICED TEA", "price": "10.00€", "description": ""},
        {"name": "APEROL SPRITZ", "price": "9.00€", "description": ""},
        {"name": "APPLE MARTINI", "price": "10.00€", "description": ""},
        {"name": "SCORPION", "price": "9.00€", "description": ""},
        {"name": "STRAWBERRY SOUR", "price": "9.00€", "description": ""},
        {"name": "PINK MASTIC", "price": "9.00€", "description": ""},
        {"name": "COOLER THAN A CUCUMBER", "price": "10.00€", "description": ""},
        {"name": "ORNAMAJO", "price": "10.00€", "description": ""},
        {"name": "TEQUILA SUNRISE", "price": "9.00€", "description": ""},
        {"name": "PALOMA", "price": "9.00€", "description": ""},
        {"name": "PORN STAR", "price": "9.00€", "description": ""},
        {"name": "HENDRICKS KING", "price": "12.00€", "description": ""},
        {"name": "BITTER SWEET SYMPHONY", "price": "12.00€", "description": ""},
        {"name": "LOVE POTION", "price": "10.00€", "description": ""},
        {"name": "ZOMBIE", "price": "12.00€", "description": ""},
        {"name": "SWIMMING POOL", "price": "10.00€", "description": ""},
        {"name": "MIAMI BEACH", "price": "10.00€", "description": ""},
        {"name": "SUFFERING BASTARD", "price": "10.00€", "description": ""},
        {"name": "BLUE MASTIC", "price": "9.00€", "description": ""},
        {"name": "POM THUMB", "price": "8.00€", "description": ""},
        {"name": "MAIAMI BEACH", "price": "12.00€", "description": ""},
        {"name": "MILANO TORINO", "price": "9.00€", "description": ""},
        {"name": "LONDON DRY", "price": "8.00€", "description": ""},
        {"name": "HAVANA GLUB", "price": "9.00€", "description": ""},
        {"name": "VERA CRUZ", "price": "14.00€", "description": ""},
        {"name": "MOSCW MULE", "price": "10.00€", "description": ""},
        {"name": "ESPRESSO MARTINI", "price": "12.00€", "description": ""},
        {"name": "BUBBLE TROUBLE", "price": "12.00€", "description": ""},
        {"name": "FLORA", "price": "12.00€", "description": ""},
        {"name": "ELEMAKULE", "price": "14.00€", "description": ""},
        {"name": "VAMONOS", "price": "13.00€", "description": ""},
        {"name": "BLUE HAWAI", "price": "8.00€", "description": ""},
        {"name": "B 52", "price": "9.00€", "description": ""}
    ],
    "ΣΦΗΝΑΚΙΑ": [
        {"name": "ΣΦΗΝΑΚΙ ΑΠΛΟ", "price": "3.00€", "description": ""},
        {"name": "ΣΦΗΝΑΚΙ ΣΠΕΣΙΑΛ", "price": "4.00€", "description": ""},
        {"name": "ΣΦΗΝΑΚΙ ΥΠΟΒΡΗΧΙΟ", "price": "5.00€", "description": ""},
        {"name": "ΣΦΗΝΑΚΙ ΠΙΓΚΟΥΙΝΟΣ", "price": "7.00€", "description": ""},
        {"name": "ΣΦΗΝΑΚΙ jagerbomp", "price": "5.00€", "description": ""}
    ],
    "ΣΟΥΒΛΑΚΙ-ΨΗΣΤΑΡΙΑ": [
        {"name": "ΠΙΤΑ ΜΕ ΓΥΡΟ ΧΟΙΡΙΝΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΚΑΛΑΜΑΚΙ ΧΟΙΡΙΝΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΚΑΛΑΜΑΚΙ ΚΟΤΟΠΟΥΛΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΜΠΙΦΤΕΚΙ ΜΟΣΧΑΡΙΣΙΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΚΕΜΠΑΠ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΚΕΜΠΑΠ ΓΕΜΙΣΤΟ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΠΑΝΣΕΤΑ ΧΟΙΡΙΝΗ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΝΤΟΝΕΡ 2 ΤΕΜΑΧΙΩΝ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΚΑΛΑΜΑΚΙ ΚΟΤΟΜΠΕΙΚΟΝ", "price": "5.00€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΜΠΙΦΤΕΚΙ ΛΑΧΑΝΙΚΩΝ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΜΕ ΓΑΡΙΔΑ", "price": "4.50€", "description": ""},
        {"name": "ΠΙΤΑ ΑNEΥ ΚΡΕΑΤΟΣ", "price": "3.00€", "description": ""},
        {"name": "ΠΙΤΑ ΤΕΜΑΧΙΟ", "price": "0.50€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΓΥΡΟ ΧΟΙΡΙΝΟ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΚΑΛΑΜΑΚΙ ΧΟΙΡΙΝΟ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΚΑΛΑΜΑΚΙ ΚΟΤΟΠΟΥΛΟ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΜΠΙΦΤΕΚΙ ΜΟΣΧΑΡΙΣΙΟ", "price": "7.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΚΕΜΠΑΠ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΜΕ ΚΕΜΠΑΠ ΓΕΜΙΣΤΟ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΠΑΝΣΕΤΑ ΧΟΙΡΙΝΗ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΝΤΟΝΕΡ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΜΕ ΚΑΛΑΜΑΚΙ ΚΟΤΟΜΠΕΙΚΟΝ", "price": "7.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΜΕ ΜΠΙΦΤΕΚΙ ΛΑΧΑΝΙΚΩΝ", "price": "6.00€", "description": ""},
        {"name": "ΨΩΜΑΚΙ ΑΝΕΥ ΚΡΕΑΤΟΣ", "price": "3.50€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΓΥΡΟ ΧΟΙΡΙΝΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΚΑΛΑΜΑΚΙ ΧΟΡΙΝΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΚΑΛΑΜΑΚΙ ΚΟΤΟΠΟΥΛΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΜΠΙΦΤΕΚΙ ΜΟΣΧΑΡΙΣΙΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΚΕΜΠΑΠ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΚΕΜΠΑΠ ΓΕΜΙΣΤΟ", "price": "10.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΝΤΟΝΕΡ", "price": "11.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΝΤΟΝΕΡ 4 ΤΕΜΑΧΙΑ", "price": "11.00€", "description": ""},
        {"name": "ΜΕΡΙΔΑ ΜΕ 3 ΚΑΛΑΜΑΚΙΑ ΚΟΤΟΜΠΕΙΚΟΝ", "price": "11.50€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΜΕΓΑΛΗ ΓΥΡΟ ΧΟΙΡΙΝΟ", "price": "11.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΜΕΓΑΛΗ ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ", "price": "11.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ", "price": "9.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΓΥΡΟ ΚΟΤΟΠΟΥΛΟ ΜΕΣΑΙΑ", "price": "9.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΓΥΡΟ ΜΕΣΑΙΑ ΧΟΙΡΙΝΟ", "price": "9.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΜΕΓΑΛΗ ΠΑΝΣΕΤΑ 4ΤΕΜ", "price": "11.00€", "description": ""},
        {"name": "ΠΙΤΑ CLUB ΠΑΝΣΕΤΑ ΜΕΣΑΙΑ ΧΟΙΡΙΝΗ 4 ΤΕΜ", "price": "9.00€", "description": ""},
        {"name": "ΚΑΛΑΜΑΚΙ ΧΟΙΡΙΝΟ ΤΕΜΑΧΙΟ", "price": "2.50€", "description": ""},
        {"name": "ΚΑΛΑΜΑΚΙ ΚΟΤΟΠΟΥΛΟ ΤΕΜΑΧΙΟ", "price": "2.50€", "description": ""},
        {"name": "ΣΟΥΒΛΑΚΙ ΧΟΙΡΙΝΟ (ΤΕΜ)", "price": "2.50€", "description": ""},
        {"name": "ΣΟΥΒΛΑΚΙ ΚΟΤΟΠΟΥΛΟ (ΤΕΜ)", "price": "2.50€", "description": ""},
        {"name": "ΚΟΤΟΜΠΕΙΚΟΝ ΤΕΜΑΧΙΟ", "price": "3.00€", "description": ""},
        {"name": "ΣΟΥΒΛΑΚΙ ΚΟΤΟΜΠΕΙΚΟΝ ΤΕΜ", "price": "3.00€", "description": ""},
        {"name": "ΜΠΙΦΤΕΚΙ ΜΟΣΧΑΡΙΣΙΟ ΤΕΜ", "price": "3.00€", "description": ""},
        {"name": "ΚΕΜΠΑΠ ΑΠΛΟ ΤΕΜ", "price": "2.50€", "description": ""},
        {"name": "ΚΕΜΠΑΠ ΓΕΜΙΣΤΟ ΤΕΜ", "price": "2.50€", "description": ""},
        {"name": "ΠΛΑΤΟ ΚΡΕΑΤΙΚΩΝ ΜΕΣΑΙΟ", "price": "15.00€", "description": ""},
        {"name": "ΠΛΑΤΟ ΚΡΕΑΤΙΚΩΝ ΜΕΓΑΛΟ", "price": "26.00€", "description": ""}
    ],
    "BURGERS": [
        {"name": "BURGER ΜΟΣΧΑΡΙΣΙΟ ΜΕ ΕΝΑ ΜΠΙΦΤΕΚΙ", "price": "8.00€", "description": ""},
        {"name": "XL BURGER ΜΟΣΧΑΡΙΣΙΟ", "price": "12.00€", "description": ""},
        {"name": "XL BURGER ΚΟΤΟΠΟΥΛΟ", "price": "12.00€", "description": ""},
        {"name": "XL BURGER ΠΡΟΒΑΤΙΝΑ", "price": "11.50€", "description": ""},
        {"name": "XL BLACK ANGUS", "price": "18.00€", "description": ""},
        {"name": "RIBEYE", "price": "35.00€", "description": ""},
        {"name": "CLASSIC CLUB SANDWICH", "price": "10.00€", "description": ""},
        {"name": "CHICKEN CLUB SANDWICH", "price": "11.00€", "description": ""},
        {"name": "HOT DOG", "price": "9.00€", "description": ""},
        {"name": "CORN DOG", "price": "8.00€", "description": ""},
        {"name": "ΚΟΤΟΜΠΟΥΚΙΕΣ", "price": "10.00€", "description": ""},
        {"name": "ΠΑΤΑΤΑ ΜΕΡΙΔΑ", "price": "4.50€", "description": ""},
        {"name": "ΠΑΤΑΤΕΣ SPECIAL", "price": "6.00€", "description": ""},
        {"name": "ΤΟΣΤ", "price": "3.50€", "description": ""}
    ],
    "ΠΙΤΣΕΣ": [
        {"name": "PIZZA SPECIAL ΓΙΓΑΣ", "price": "14.00€", "description": ""},
        {"name": "PIZZA ΧΩΡΙΑΤΙΚΗ ΓΙΓΑΣ", "price": "14.00€", "description": ""},
        {"name": "PIZZA ΜΑΡΓΑΡΙΤΑ ΓΙΓΑΣ", "price": "14.00€", "description": ""},
        {"name": "PIZZA ΑΝΤΖΟΥΓΙΕΣ ΓΙΓΑΣ", "price": "14.00€", "description": ""},
        {"name": "PIZZA SPECIAL", "price": "13.00€", "description": ""},
        {"name": "PIZZA ΧΩΡΙΑΤΙΚΗ", "price": "14.00€", "description": ""},
        {"name": "PIZZA ΜΑΡΓΑΡΙΤΑ", "price": "11.00€", "description": ""},
        {"name": "PIZZA ΑΝΤΖΟΥΓΙΕΣ", "price": "12.00€", "description": ""},
        {"name": "PIZZA ΑΠΛΗ", "price": "11.00€", "description": ""},
        {"name": "PEPERONE", "price": "12.00€", "description": ""},
        {"name": "ΜΑΚΑΡΟΝΙΑ ΜΕ ΚΙΜΑ", "price": "11.00€", "description": ""},
        {"name": "ΜΑΚΑΡΟΝΙΑ 4 ΤΥΡΙΑ", "price": "11.00€", "description": ""},
        {"name": "ΚΑΡΜΠΟΝΑΡΑ", "price": "10.00€", "description": ""},
        {"name": "ΜΑΚΑΡΩΝΕΣ ΛΗΜΝΟΥ", "price": "9.00€", "description": ""},
        {"name": "CAESAR (ΣΑΛΑΤΑ)", "price": "10.00€", "description": ""}
    ],
    "SUSHI": [
        {"name": "SALMON ROLL", "price": "10.00€", "description": ""},
        {"name": "TERIYAKI ROLL", "price": "10.00€", "description": ""},
        {"name": "VEGGIE ROLL", "price": "9.00€", "description": ""},
        {"name": "TEMPURA ROLL", "price": "10.00€", "description": ""},
        {"name": "SURIMI ROLL", "price": "10.00€", "description": ""},
        {"name": "DIA STRAWBERRY ROLL", "price": "11.00€", "description": ""},
        {"name": "DIA AKAI ROLL", "price": "11.00€", "description": ""},
        {"name": "DIA VOLCANO ROLL", "price": "10.00€", "description": ""},
        {"name": "DIA FRIED ROLL", "price": "11.00€", "description": ""},
        {"name": "SHRIMP BAO BUN", "price": "9.00€", "description": ""},
        {"name": "CHICKEN BAO BUN", "price": "9.00€", "description": ""},
        {"name": "TEMPURA ΜΕΡΙΔΑ", "price": "8.00€", "description": ""},
        {"name": "CHIPS ΓΑΡΙΔΑΣ", "price": "3.50€", "description": ""},
        {"name": "DIA CRAB LEG SALAD", "price": "9.00€", "description": ""},
        {"name": "DIA SHRIMP AVOCADO SALAD", "price": "9.00€", "description": ""},
        {"name": "SPICY PLATTER", "price": "25.00€", "description": ""},
        {"name": "CLASSIC PLATTER", "price": "25.00€", "description": ""},
        {"name": "ΣΟΣΑΚΙ / dip", "price": "0.50€", "description": ""}
    ],
    "ΓΛΥΚΑ": [
        {"name": "ΛΟΥΚΟΥΜΑΔΕΣ", "price": "7.00€", "description": ""},
        {"name": "ΛΟΥΚΟΥΜΑΔΕΣ DIA NOCHE", "price": "22.00€", "description": ""},
        {"name": "ΛΟΥΚΟΥΜΑΔΕΣ ΠΑΚΕΤΟ", "price": "9.00€", "description": ""},
        {"name": "ΓΛΥΚΙΑ ΚΡΕΠΑ", "price": "5.00€", "description": ""},
        {"name": "ΚΡΕΠΑ ΑΛΜΥΡΗ", "price": "5.00€", "description": ""},
        {"name": "ΒΑΦΛΑ ΓΛΥΚΙΑ", "price": "5.00€", "description": ""},
        {"name": "ΒΑΦΛΑ ΑΛΜΥΡΗ", "price": "5.00€", "description": ""},
        {"name": "ΣΟΥΦΛΕ ΣΟΚΟΛΑΤΑΣ", "price": "5.00€", "description": ""},
        {"name": "KAZANDIBI", "price": "6.00€", "description": ""},
        {"name": "ΜΟΥΣ ΣΟΚΟΛΑΤΑ", "price": "4.00€", "description": ""},
        {"name": "ΚΟΡΜΟΣ", "price": "5.00€", "description": ""},
        {"name": "CHEESCAKE", "price": "6.50€", "description": ""},
        {"name": "ΠΑΝΑΚΟΤΑ", "price": "4.00€", "description": ""},
        {"name": "ΠΟΡΤΟΚΑΛΟΠΙΤΑ", "price": "5.00€", "description": ""},
        {"name": "ΣΟΚΟΛΑΤΟΠΙΤΑ", "price": "6.00€", "description": ""},
        {"name": "ΤΗΓΑΝΙΤΑ ΛΗΜΝΟΥ ΜΕ ΜΕΛΙ", "price": "7.00€", "description": ""},
        {"name": "1 ΜΠΑΛΑ ΠΑΓΩΤΟ", "price": "3.50€", "description": ""},
        {"name": "2 ΜΠΑΛΕΣ ΠΑΓΩΤΟ", "price": "7.00€", "description": ""},
        {"name": "3 ΜΠΑΛΕΣ ΠΑΓΩΤΟ", "price": "10.50€", "description": ""},
        {"name": "4 ΜΠΑΛΕΣ ΠΑΓΩΤΟ", "price": "14.00€", "description": ""},
        {"name": "ΦΡΟΥΤΟΣΑΛΑΤΑ", "price": "7.00€", "description": ""},
        {"name": "ΓΙΑΟΥΡΤΙ ΜΕ ΔΗΜΗΤΡΙΑΚΑ", "price": "8.00€", "description": ""},
        {"name": "ΓΙΑΟΥΡΤΙ ΜΕ ΦΡΟΥΤΑ ΚΑΙ ΜΕΛΙ", "price": "6.50€", "description": ""},
        {"name": "ΟΜΕΛΕΤΑ SPECIAL", "price": "10.00€", "description": ""},
        {"name": "ΜΠΟΥΓΑΤΣΑ ΚΡΕΜΑ / ΤΥΡΙ", "price": "5.00€", "description": ""}
    ],
    "PANCAKES": [
        {"name": "PANCAKE ΓΛΥΚΟ", "price": "5.00€", "description": ""},
        {"name": "PANCAKE ΑΛΜΥΡΟ", "price": "5.00€", "description": ""},
        {"name": "ΑΥΓΟΦΕΤΕΣ ΓΛΥΚΕΣ", "price": "6.00€", "description": ""},
        {"name": "ΑΥΓΟΦΕΤΕΣ ΑΛΜΥΡΕΣ", "price": "7.50€", "description": ""}
    ]
}

@app.route('/')
def home():
  
    return render_template('home.html', categories=menu_categories)

@app.route('/category/<category_name>')
def show_category(category_name):
   
    category_name_upper = category_name.upper()
    
    
    if category_name_upper in menu_products:
        products = menu_products.get(category_name_upper, [])
        return render_template('index.html', category=category_name_upper, products=products)
    else:
        
        return render_template('index.html', category=category_name_upper, products=[])

if __name__ == '__main__':
    
    menu_url = "http://10.0.10.132:5000/"
    
    
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(menu_url)
    qr.make(fit=True)
    
    
    img = qr.make_image(fill_color="black", back_color="white")
    img.save("menu_qr.png")
    print("🚀 Το ΝΕΟ QR Code δημιουργήθηκε με επιτυχία!")
    
    
    app.run(host="0.0.0.0", debug=True)